apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-postgresql-local
data:
  DB_NAME: myposgres
  DB_USER: myuser
  DB_HOST: myhost
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: bXlwYXNzd29yZA==